name: tabame
description: Tabame is a quick menu app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  contextual_menu: ^0.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  tabamewin32:
    path: tabamewin32
  win32: ^2.7.0
  window_manager: ^0.2.5

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    # - resources/logo.png
    - resources/logo_light.png
    - resources/wizzard1.png