part of 'launcher_design.dart';

/// Search, frame and dialog defaults kept together for each launcher design.
@immutable
class LauncherDesignConfig {
  const LauncherDesignConfig({
    this.searchIcon = Icons.search_rounded,
    this.searchIconSize = 20.0,
    this.searchFontSize = 15.0,
    this.searchFontWeight = FontWeight.w500,
    required this.frameRadius,
    required this.controlRadius,
    this.searchIconUsesOnSurface = false,
    this.searchHint,
    this.resultsListPadding = const EdgeInsets.all(8),
    this.isQuickMenuInspired = false,
    this.usesDesignFont = false,
    this.outlinedControls = false,
  });

  final IconData searchIcon;
  final double searchIconSize;
  final double searchFontSize;
  final FontWeight? searchFontWeight;
  final double frameRadius;
  final double controlRadius;
  final bool searchIconUsesOnSurface;
  final String? searchHint;
  final EdgeInsets resultsListPadding;
  final bool isQuickMenuInspired;
  final bool usesDesignFont;
  final bool outlinedControls;

  factory LauncherDesignConfig.forDesign(LauncherDesign design) => switch (design) {
        LauncherDesign.thermal => const LauncherDesignConfig(
            searchFontSize: 18.0,
            frameRadius: 10.0,
            controlRadius: 5.0,
            usesDesignFont: true,
          ),
        LauncherDesign.capillary => const LauncherDesignConfig(
            searchFontSize: 18.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 8.0,
            controlRadius: 4.0,
            usesDesignFont: true,
          ),
        LauncherDesign.liquidMetal => const LauncherDesignConfig(
            searchIconSize: 22.0,
            searchFontSize: 20.0,
            frameRadius: 16.0,
            controlRadius: 8.0,
            usesDesignFont: true,
          ),
        LauncherDesign.opticalGlass => const LauncherDesignConfig(
            searchIconSize: 22.0,
            searchFontSize: 20.0,
            frameRadius: 24.0,
            controlRadius: 12.0,
            usesDesignFont: true,
          ),
        LauncherDesign.command => const LauncherDesignConfig(
            searchIcon: Icons.chevron_right_rounded,
            searchIconSize: 22.0,
            frameRadius: 12.0,
            controlRadius: 6.0,
            outlinedControls: true,
          ),
        LauncherDesign.terminal => const LauncherDesignConfig(
            searchIcon: Icons.chevron_right_rounded,
            searchFontSize: 14.0,
            frameRadius: 6.0,
            controlRadius: 3.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.zen => const LauncherDesignConfig(
            searchIcon: Icons.eco_rounded,
            frameRadius: 26.0,
            controlRadius: 16.0,
            usesDesignFont: true,
          ),
        LauncherDesign.serene => const LauncherDesignConfig(
            searchIconSize: 22.0,
            searchFontSize: 16.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 14.0,
            controlRadius: 10.0,
            searchIconUsesOnSurface: true,
          ),
        LauncherDesign.glass => const LauncherDesignConfig(
            searchFontSize: 16.0,
            frameRadius: 28.0,
            controlRadius: 14.0,
            searchIconUsesOnSurface: true,
            usesDesignFont: true,
          ),
        LauncherDesign.classic => const LauncherDesignConfig(
            searchFontWeight: null,
            frameRadius: 18.0,
            controlRadius: 10.0,
          ),
        LauncherDesign.blueprint => const LauncherDesignConfig(
            searchIcon: Icons.architecture_rounded,
            frameRadius: 3.0,
            controlRadius: 2.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.transit => const LauncherDesignConfig(
            searchIcon: Icons.near_me_rounded,
            searchIconSize: 16.0,
            searchFontWeight: FontWeight.w600,
            frameRadius: 16.0,
            controlRadius: 8.0,
            usesDesignFont: true,
          ),
        LauncherDesign.fluent => const LauncherDesignConfig(
            searchIconSize: 18.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 8.0,
            controlRadius: 4.0,
            searchIconUsesOnSurface: true,
            usesDesignFont: true,
          ),
        LauncherDesign.manifesto => const LauncherDesignConfig(
            searchIcon: Icons.arrow_forward,
            searchIconSize: 18.0,
            searchFontSize: 17.0,
            searchFontWeight: FontWeight.w600,
            frameRadius: 0.0,
            controlRadius: 0.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.orbit => const LauncherDesignConfig(
            searchIcon: Icons.radar,
            searchIconSize: 19.0,
            frameRadius: 10.0,
            controlRadius: 4.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.anime => const LauncherDesignConfig(
            searchIcon: Icons.auto_awesome_rounded,
            searchIconSize: 19.0,
            searchFontSize: 16.0,
            frameRadius: 16.0,
            controlRadius: 12.0,
            usesDesignFont: true,
          ),
        LauncherDesign.tech => const LauncherDesignConfig(
            searchIcon: Icons.memory_rounded,
            searchIconSize: 19.0,
            searchFontWeight: FontWeight.w600,
            frameRadius: 10.0,
            controlRadius: 8.0,
            isQuickMenuInspired: true,
          ),
        LauncherDesign.vector => const LauncherDesignConfig(
            searchIcon: Icons.radar_rounded,
            searchIconSize: 18.0,
            searchFontWeight: FontWeight.w600,
            frameRadius: 4.0,
            controlRadius: 4.0,
            isQuickMenuInspired: true,
          ),
        LauncherDesign.outrun => const LauncherDesignConfig(
            searchIcon: Icons.bolt_rounded,
            searchFontSize: 16.0,
            searchFontWeight: FontWeight.w700,
            frameRadius: 0.0,
            controlRadius: 0.0,
            isQuickMenuInspired: true,
          ),
        LauncherDesign.matrix => const LauncherDesignConfig(
            searchIcon: Icons.terminal_rounded,
            searchIconSize: 18.0,
            searchFontSize: 14.0,
            frameRadius: 2.0,
            controlRadius: 2.0,
            isQuickMenuInspired: true,
          ),
        LauncherDesign.steam => const LauncherDesignConfig(
            searchIcon: Icons.settings_rounded,
            searchIconSize: 18.0,
            searchFontWeight: FontWeight.w600,
            frameRadius: 6.0,
            controlRadius: 6.0,
            isQuickMenuInspired: true,
          ),
        LauncherDesign.cyber => const LauncherDesignConfig(
            searchIcon: Icons.hub_rounded,
            searchIconSize: 19.0,
            searchFontWeight: FontWeight.w600,
            frameRadius: 4.0,
            controlRadius: 4.0,
            isQuickMenuInspired: true,
          ),
        LauncherDesign.manga => const LauncherDesignConfig(
            searchIcon: Icons.auto_stories_rounded,
            searchIconSize: 19.0,
            searchFontSize: 16.0,
            searchFontWeight: FontWeight.w700,
            frameRadius: 14.0,
            controlRadius: 10.0,
            isQuickMenuInspired: true,
          ),
        LauncherDesign.windowsXp => const LauncherDesignConfig(
            searchIcon: Icons.search,
            searchIconSize: 18.0,
            searchFontSize: 14.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 7.0,
            controlRadius: 0.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.windows98 => const LauncherDesignConfig(
            searchIcon: Icons.search,
            searchIconSize: 16.0,
            searchFontSize: 13.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 0.0,
            controlRadius: 0.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.notion => const LauncherDesignConfig(
            searchIconSize: 17.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 8.0,
            controlRadius: 4.0,
            searchIconUsesOnSurface: true,
            usesDesignFont: true,
          ),
        LauncherDesign.switchboard => const LauncherDesignConfig(
            searchIcon: Icons.tune_rounded,
            searchIconSize: 18.0,
            frameRadius: 4.0,
            controlRadius: 3.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.relay => const LauncherDesignConfig(
            searchIcon: Icons.alt_route_rounded,
            searchIconSize: 18.0,
            searchFontSize: 16.0,
            searchFontWeight: FontWeight.w600,
            frameRadius: 7.0,
            controlRadius: 3.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.terminal2 => const LauncherDesignConfig(
            searchIcon: Icons.terminal_rounded,
            searchFontSize: 14.0,
            frameRadius: 2.0,
            controlRadius: 2.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.newCast => const LauncherDesignConfig(
            searchIcon: Icons.chevron_right_rounded,
            searchIconSize: 18.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 14.0,
            controlRadius: 8.0,
            searchIconUsesOnSurface: true,
            searchHint: 'Search apps, files, and commands...',
            usesDesignFont: true,
          ),
        LauncherDesign.omarchy => const LauncherDesignConfig(
            searchIcon: Icons.drag_indicator,
            searchIconSize: 16.0,
            searchFontSize: 16.0,
            frameRadius: 0.0,
            controlRadius: 0.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.aurora => const LauncherDesignConfig(
            searchIconSize: 28.0,
            searchFontSize: 23.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 18.0,
            controlRadius: 10.0,
            usesDesignFont: true,
          ),
        LauncherDesign.crt => const LauncherDesignConfig(
            searchFontSize: 23.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 18.0,
            controlRadius: 2.0,
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.phosphor => const LauncherDesignConfig(
            searchFontSize: 23.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 0.0,
            controlRadius: 0.0,
            usesDesignFont: true,
          ),
        LauncherDesign.retro => const LauncherDesignConfig(
            searchIcon: Icons.videogame_asset_rounded,
            searchFontSize: 20.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 8.0,
            controlRadius: 0.0,
            searchHint: 'TYPE TO SEARCH...',
            resultsListPadding: EdgeInsets.symmetric(horizontal: 4, vertical: 6),
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.toon => const LauncherDesignConfig(
            searchIcon: Icons.auto_awesome_rounded,
            searchFontSize: 18.0,
            searchFontWeight: FontWeight.w700,
            frameRadius: 8.0,
            controlRadius: 5.0,
            searchHint: 'SEARCH THE ARCHIVE...',
            resultsListPadding: EdgeInsets.symmetric(horizontal: 6, vertical: 4),
            usesDesignFont: true,
            outlinedControls: true,
          ),
        LauncherDesign.strata => const LauncherDesignConfig(
            searchIconSize: 28.0,
            searchFontSize: 23.0,
            searchFontWeight: FontWeight.w400,
            frameRadius: 12.0,
            controlRadius: 8.0,
            usesDesignFont: true,
          ),
        LauncherDesign.tui => LauncherDesignConfig(
            searchIcon: Icons.terminal,
            searchIconSize: 16.0,
            searchFontSize: TuiTokens.fontSize,
            searchFontWeight: FontWeight.w400,
            frameRadius: 0.0,
            controlRadius: 0.0,
            searchHint: '',
            resultsListPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
            usesDesignFont: true,
            outlinedControls: true,
          ),
      };
}
