import 'dart:ui';

import 'classes/saved_maps.dart';
import 'settings.dart';

enum QuickMenuDesigns {
  classic,
  modern,
  serene,
  matrix,
  interface,
  aurora,
  terminal,
  terminal2,
  cassette,
  fluent,
  gazette,
  player,
  steam,
  manifesto,
  vector,
  ledger,
  console,
  console2,
  foundry,
  anime,
  anime2,
  cyber,
  tech,
  manga,
  outrun,
  outrun2,
  winamp,
  windowsXp,
  windows98,
  notion,
  rundown,
  commandDeck,
  switchboard,
  orbit,
  tui,
  crt,
  retro,
  superMario,
  ivoryGrove,
  ukiyoe,
  radiant,
  nouveau,
  satin,
  liquidMetal,
  opticalGlass,
  ;

  String get displayName => switch (this) {
        QuickMenuDesigns.ivoryGrove => 'Ivory Grove',
        QuickMenuDesigns.ukiyoe => 'Ukiyo-e',
        QuickMenuDesigns.liquidMetal => 'Liquid Metal',
        QuickMenuDesigns.opticalGlass => 'Optical Glass',
        QuickMenuDesigns.windowsXp => 'Windows XP',
        QuickMenuDesigns.windows98 => 'Windows 98',
        QuickMenuDesigns.commandDeck => 'Command Deck',
        QuickMenuDesigns.tui => 'TUI',
        QuickMenuDesigns.crt => 'CRT',
        QuickMenuDesigns.superMario => 'SuperMario',
        _ => name.toUpperCaseFirst(),
      };
}

enum LauncherDesign {
  classic,
  serene,
  command,
  terminal,
  terminal2,
  zen,
  glass,
  blueprint,
  transit,
  fluent,
  manifesto,
  orbit,
  anime,
  tech,
  vector,
  outrun,
  matrix,
  steam,
  cyber,
  manga,
  windowsXp,
  windows98,
  notion,
  switchboard,
  relay,
  newCast,
  omarchy,
  tui,
  aurora,
  strata,
  phosphor,
  liquidMetal,
  opticalGlass,
  crt,
  retro,
  toon,
  capillary,
  thermal,
  satin,
  nouveau,
  radiant,
  ukiyoe,
  ivoryGrove;

  String get displayName => switch (this) {
        LauncherDesign.ivoryGrove => 'Ivory Grove',
        LauncherDesign.ukiyoe => 'Ukiyo-e',
        LauncherDesign.crt => 'CRT',
        LauncherDesign.retro => 'Retro',
        LauncherDesign.liquidMetal => 'Liquid Metal',
        LauncherDesign.opticalGlass => 'Optical Glass',
        LauncherDesign.toon => 'Toon',
        LauncherDesign.windowsXp => 'Windows XP',
        LauncherDesign.tui => 'TUI',
        LauncherDesign.windows98 => 'Windows 98',
        _ => name.toUpperCaseFirst(),
      };
}

class DesignSettings {
  static ThemeColors defaultThemeColors({
    required Color background,
    required Color textColor,
    required Color accentColor,
    required int gradientAlpha,
    String uiFontFamily = 'Jura',
    int uiFontWeight = 400,
    bool uiFontItalic = false,
    String entryFontFamily = 'Jura',
    int entryFontWeight = 700,
    bool entryFontItalic = false,
    double borderRadius = 10,
    double baseFontSize = 10,
  }) {
    return ThemeColors(
      background: background,
      text: textColor,
      accent: accentColor,
      gradientAlpha: gradientAlpha,
      uiFontFamily: uiFontFamily,
      uiFontWeight: uiFontWeight,
      uiFontItalic: uiFontItalic,
      entryFontFamily: entryFontFamily,
      entryFontWeight: entryFontWeight,
      entryFontItalic: entryFontItalic,
      borderRadius: borderRadius,
      baseFontSize: baseFontSize,
    );
  }

  static Map<String, LauncherDesignThemeSet> createDefaultLauncherDesignThemes() {
    final Map<String, QMDesignThemeSet> quickMenuDefaults = createDefaultQuickMenuDesignThemes();

    LauncherDesignThemeSet fromQuickMenu(QuickMenuDesigns design) {
      final QMDesignThemeSet source = quickMenuDefaults[design.displayName] ?? quickMenuDefaults[design.name]!;
      return LauncherDesignThemeSet(
        lightTheme: source.lightTheme.copyWith(),
        darkTheme: source.darkTheme.copyWith(),
      );
    }

    return <String, LauncherDesignThemeSet>{
      LauncherDesign.ivoryGrove.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF0EADF),
          textColor: const Color(0xFF39362F),
          accentColor: const Color(0xFFAC8845),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 600,
          borderRadius: 20,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF292720),
          textColor: const Color(0xFFF0E9DC),
          accentColor: const Color(0xFFD0B477),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 600,
          borderRadius: 20,
          baseFontSize: 10,
        ),
      ),
      LauncherDesign.classic.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffD5E0FB),
          textColor: const Color(0xff3A404A),
          accentColor: const Color(0xff446EE9),
          gradientAlpha: 200,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF0A0A0A),
          textColor: const Color(0xFFFAF9F8),
          accentColor: const Color(0xFFA7CF3F),
          gradientAlpha: 20,
        ),
      ),
      LauncherDesign.serene.displayName: fromQuickMenu(QuickMenuDesigns.serene),
      LauncherDesign.command.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFE8E9E2),
          textColor: const Color(0xFF171A17),
          accentColor: const Color(0xFF2F6B50),
          gradientAlpha: 28,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 500,
          entryFontFamily: 'Segoe UI Variable Text',
          entryFontWeight: 600,
          borderRadius: 12,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF151815),
          textColor: const Color(0xFFE4E8DE),
          accentColor: const Color(0xFFC3E56A),
          gradientAlpha: 36,
          uiFontFamily: 'Bahnschrift',
          entryFontFamily: 'Segoe UI Variable Text',
          entryFontWeight: 600,
          borderRadius: 12,
        ),
      ),
      LauncherDesign.terminal.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF4F4F1),
          textColor: const Color(0xFF2A2A2A),
          accentColor: const Color(0xFF00A896),
          gradientAlpha: 0,
          uiFontFamily: 'JetBrains Mono',
          uiFontWeight: 500,
          entryFontFamily: 'JetBrains Mono',
          entryFontWeight: 600,
          borderRadius: 6,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF0C0C0C),
          textColor: const Color(0xFFCCCCCC),
          accentColor: const Color(0xFF39D353),
          gradientAlpha: 0,
          uiFontFamily: 'JetBrains Mono',
          uiFontWeight: 500,
          entryFontFamily: 'JetBrains Mono',
          entryFontWeight: 600,
          borderRadius: 6,
        ),
      ),
      LauncherDesign.terminal2.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF2F1E8),
          textColor: const Color(0xFF242A20),
          accentColor: const Color(0xFF9A5D16),
          gradientAlpha: 0,
          uiFontFamily: 'Fragment Mono',
          uiFontWeight: 500,
          entryFontFamily: 'Fragment Mono',
          entryFontWeight: 600,
          borderRadius: 2,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF10130F),
          textColor: const Color(0xFFE4E7D5),
          accentColor: const Color(0xFFE8B86A),
          gradientAlpha: 0,
          uiFontFamily: 'Fragment Mono',
          uiFontWeight: 500,
          entryFontFamily: 'Fragment Mono',
          entryFontWeight: 600,
          borderRadius: 2,
        ),
      ),
      LauncherDesign.omarchy.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF5EEDC),
          textColor: const Color(0xFF3C3836),
          accentColor: const Color(0xFF596B32),
          gradientAlpha: 0,
          uiFontFamily: 'Inconsolata',
          entryFontFamily: 'Inconsolata',
          borderRadius: 0,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF282828),
          textColor: const Color(0xFFD4BE98),
          accentColor: const Color(0xFFA9B665),
          gradientAlpha: 0,
          uiFontFamily: 'Inconsolata',
          entryFontFamily: 'Inconsolata',
          borderRadius: 0,
        ),
      ),
      LauncherDesign.tui.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF2F2F2),
          textColor: const Color(0xFF0C0C0C),
          accentColor: const Color(0xFF0037DA),
          gradientAlpha: 0,
          uiFontFamily: 'Consolas',
          entryFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontWeight: 400,
          borderRadius: 0,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF0C0C0C),
          textColor: const Color(0xFFCCCCCC),
          accentColor: const Color(0xFFCCCCCC),
          gradientAlpha: 0,
          uiFontFamily: 'Consolas',
          entryFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontWeight: 400,
          borderRadius: 0,
        ),
      ),
      LauncherDesign.zen.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFEEF1E6),
          textColor: const Color(0xFF3C463B),
          accentColor: const Color(0xFF7B9A6B),
          gradientAlpha: 0,
          uiFontFamily: 'Quicksand',
          entryFontFamily: 'Quicksand',
          entryFontWeight: 600,
          borderRadius: 26,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF171C18),
          textColor: const Color(0xFFD7DFCF),
          accentColor: const Color(0xFF93B281),
          gradientAlpha: 0,
          uiFontFamily: 'Quicksand',
          entryFontFamily: 'Quicksand',
          entryFontWeight: 600,
          borderRadius: 26,
        ),
      ),
      LauncherDesign.glass.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFE8EEF9),
          textColor: const Color(0xFF26354A),
          accentColor: const Color(0xFF4A78D1),
          gradientAlpha: 0,
          uiFontFamily: 'Inter',
          entryFontFamily: 'Inter',
          entryFontWeight: 500,
          borderRadius: 28,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF11151D),
          textColor: const Color(0xFFE6ECF7),
          accentColor: const Color(0xFF8AAEF5),
          gradientAlpha: 0,
          uiFontFamily: 'Inter',
          entryFontFamily: 'Inter',
          entryFontWeight: 500,
          borderRadius: 28,
        ),
      ),
      LauncherDesign.blueprint.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFD9D8FF),
          textColor: const Color(0xFF1F4467),
          accentColor: const Color(0xFF2E6DA4),
          gradientAlpha: 0,
          uiFontFamily: 'Chakra Petch',
          entryFontFamily: 'Chakra Petch',
          borderRadius: 3,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF0C2841),
          textColor: const Color(0xFFD9EAF8),
          accentColor: const Color(0xFF7FB8E6),
          gradientAlpha: 0,
          uiFontFamily: 'Chakra Petch',
          entryFontFamily: 'Chakra Petch',
          borderRadius: 3,
        ),
      ),
      LauncherDesign.transit.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF7F7F4),
          textColor: const Color(0xFF17191C),
          accentColor: const Color(0xFFDF3F55),
          gradientAlpha: 0,
          uiFontFamily: 'Overpass',
          entryFontFamily: 'Overpass',
          entryFontWeight: 600,
          borderRadius: 16,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF15181D),
          textColor: const Color(0xFFE9EDF2),
          accentColor: const Color(0xFF0E5D57),
          gradientAlpha: 0,
          uiFontFamily: 'Overpass',
          entryFontFamily: 'Overpass',
          entryFontWeight: 600,
          borderRadius: 16,
        ),
      ),
      LauncherDesign.fluent.displayName: fromQuickMenu(QuickMenuDesigns.fluent),
      LauncherDesign.manifesto.displayName: fromQuickMenu(QuickMenuDesigns.manifesto),
      LauncherDesign.orbit.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFEEF3EF),
          textColor: const Color(0xFF1C2A28),
          accentColor: const Color(0xFFB8662F),
          gradientAlpha: 0,
          uiFontFamily: 'Space Grotesk',
          entryFontFamily: 'Space Grotesk',
          entryFontWeight: 600,
          borderRadius: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF04090E),
          textColor: const Color(0xFFD9E8E4),
          accentColor: const Color(0xFF63D6B4),
          gradientAlpha: 0,
          uiFontFamily: 'Space Grotesk',
          entryFontFamily: 'Space Grotesk',
          entryFontWeight: 600,
          borderRadius: 10,
        ),
      ),
      LauncherDesign.anime.displayName: fromQuickMenu(QuickMenuDesigns.anime),
      LauncherDesign.tech.displayName: fromQuickMenu(QuickMenuDesigns.tech),
      LauncherDesign.vector.displayName: fromQuickMenu(QuickMenuDesigns.vector),
      LauncherDesign.outrun.displayName: fromQuickMenu(QuickMenuDesigns.outrun2),
      LauncherDesign.matrix.displayName: fromQuickMenu(QuickMenuDesigns.matrix),
      LauncherDesign.steam.displayName: fromQuickMenu(QuickMenuDesigns.steam),
      LauncherDesign.cyber.displayName: fromQuickMenu(QuickMenuDesigns.cyber),
      LauncherDesign.manga.displayName: fromQuickMenu(QuickMenuDesigns.manga),
      LauncherDesign.windowsXp.displayName: fromQuickMenu(QuickMenuDesigns.windowsXp),
      LauncherDesign.windows98.displayName: fromQuickMenu(QuickMenuDesigns.windows98),
      LauncherDesign.notion.displayName: fromQuickMenu(QuickMenuDesigns.notion),
      LauncherDesign.switchboard.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFEDF0EB),
          textColor: const Color(0xFF1C251F),
          accentColor: const Color(0xFF4E9B73),
          gradientAlpha: 0,
          uiFontFamily: 'Public Sans',
          entryFontFamily: 'Public Sans',
          entryFontWeight: 600,
          borderRadius: 4,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF141816),
          textColor: const Color(0xFFE8EEE9),
          accentColor: const Color(0xFF8CCFA7),
          gradientAlpha: 0,
          uiFontFamily: 'Public Sans',
          entryFontFamily: 'Public Sans',
          entryFontWeight: 600,
          borderRadius: 4,
        ),
      ),
      LauncherDesign.relay.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF2F0E9),
          textColor: const Color(0xFF25232A),
          accentColor: const Color(0xFFB36B4B),
          gradientAlpha: 0,
          uiFontFamily: 'Encode Sans',
          entryFontFamily: 'Encode Sans',
          entryFontWeight: 600,
          borderRadius: 7,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF18181D),
          textColor: const Color(0xFFECEAF0),
          accentColor: const Color(0xFFD68C67),
          gradientAlpha: 0,
          uiFontFamily: 'Encode Sans',
          entryFontFamily: 'Encode Sans',
          entryFontWeight: 600,
          borderRadius: 7,
        ),
      ),
      LauncherDesign.ukiyoe.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF2E6CB),
          textColor: const Color(0xFF243C48),
          accentColor: const Color(0xFF244F6A),
          gradientAlpha: 0,
          uiFontFamily: 'Zen Kaku Gothic New',
          entryFontFamily: 'Zen Kaku Gothic New',
          entryFontWeight: 500,
          borderRadius: 6,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF1D2C35),
          textColor: const Color(0xFFE9DCC0),
          accentColor: const Color(0xFF8DAFBE),
          gradientAlpha: 0,
          uiFontFamily: 'Zen Kaku Gothic New',
          entryFontFamily: 'Zen Kaku Gothic New',
          entryFontWeight: 500,
          borderRadius: 6,
        ),
      ),
      LauncherDesign.radiant.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFD5E0FB),
          textColor: const Color(0xFF3F4ED9),
          accentColor: const Color(0xFF168BFF),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 500,
          borderRadius: 22,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF03091F),
          textColor: const Color(0xFFDCE8FF),
          accentColor: const Color(0xFF168BFF),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 500,
          borderRadius: 22,
        ),
      ),
      LauncherDesign.nouveau.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF5F1E8),
          textColor: const Color(0xFF30352B),
          accentColor: const Color(0xFF60684D),
          gradientAlpha: 0,
          uiFontFamily: 'Commissioner',
          entryFontFamily: 'Commissioner',
          entryFontWeight: 500,
          borderRadius: 18,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF23271F),
          textColor: const Color(0xFFF0EBDD),
          accentColor: const Color(0xFFB9C39B),
          gradientAlpha: 0,
          uiFontFamily: 'Commissioner',
          entryFontFamily: 'Commissioner',
          entryFontWeight: 500,
          borderRadius: 18,
        ),
      ),
      LauncherDesign.satin.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF0EFE9),
          textColor: const Color(0xFF303A36),
          accentColor: const Color(0xFF667C6E),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow',
          uiFontWeight: 500,
          entryFontFamily: 'Barlow',
          entryFontWeight: 500,
          borderRadius: 14,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF1C2320),
          textColor: const Color(0xFFE7EBE3),
          accentColor: const Color(0xFFA7BBA8),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow',
          uiFontWeight: 500,
          entryFontFamily: 'Barlow',
          entryFontWeight: 500,
          borderRadius: 14,
        ),
      ),
      LauncherDesign.thermal.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF1ECE4),
          textColor: const Color(0xFF2E3338),
          accentColor: const Color(0xFFA85F2D),
          gradientAlpha: 0,
          uiFontFamily: 'Hanken Grotesk',
          uiFontWeight: 500,
          entryFontFamily: 'Hanken Grotesk',
          entryFontWeight: 500,
          borderRadius: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF14181C),
          textColor: const Color(0xFFEEE9DF),
          accentColor: const Color(0xFFE1AD70),
          gradientAlpha: 0,
          uiFontFamily: 'Hanken Grotesk',
          uiFontWeight: 500,
          entryFontFamily: 'Hanken Grotesk',
          entryFontWeight: 500,
          borderRadius: 10,
        ),
      ),
      LauncherDesign.capillary.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF3F0E6),
          textColor: const Color(0xFF252C3C),
          accentColor: const Color(0xFF354B82),
          gradientAlpha: 0,
          uiFontFamily: 'Commissioner',
          uiFontWeight: 500,
          entryFontFamily: 'Commissioner',
          entryFontWeight: 500,
          borderRadius: 8,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF191C24),
          textColor: const Color(0xFFE8E6DE),
          accentColor: const Color(0xFF94A6D9),
          gradientAlpha: 0,
          uiFontFamily: 'Commissioner',
          uiFontWeight: 500,
          entryFontFamily: 'Commissioner',
          entryFontWeight: 500,
          borderRadius: 8,
        ),
      ),
      LauncherDesign.opticalGlass.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFE5EAF2),
          textColor: const Color(0xFF202D45),
          accentColor: const Color(0xFF435B91),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 500,
          borderRadius: 24,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF11151D),
          textColor: const Color(0xFFE6ECF7),
          accentColor: const Color(0xFF8AAEF5),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 500,
          borderRadius: 24,
        ),
      ),
      LauncherDesign.liquidMetal.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFE7EAED),
          textColor: const Color(0xFF2B3035),
          accentColor: const Color(0xFF626A73),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow',
          entryFontFamily: 'Barlow',
          entryFontWeight: 500,
          borderRadius: 16,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF12151A),
          textColor: const Color(0xFFECEAE4),
          accentColor: const Color(0xFFCEC5AF),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow',
          entryFontFamily: 'Barlow',
          entryFontWeight: 500,
          borderRadius: 16,
        ),
      ),
      LauncherDesign.crt.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
            background: const Color(0xFFF0E2C5),
            textColor: const Color(0xFF49361F),
            accentColor: const Color(0xFFB56A22),
            gradientAlpha: 0,
            uiFontFamily: 'Consolas',
            entryFontFamily: 'Consolas',
            entryFontWeight: 400,
            borderRadius: 18),
        darkTheme: defaultThemeColors(
            background: const Color(0xFF130F09),
            textColor: const Color(0xFFFFDDA0),
            accentColor: const Color(0xFFFFBE62),
            gradientAlpha: 0,
            uiFontFamily: 'Consolas',
            entryFontFamily: 'Consolas',
            entryFontWeight: 400,
            borderRadius: 18),
      ),
      LauncherDesign.retro.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF5EEE6),
          textColor: const Color(0xFF302638),
          accentColor: const Color(0xFFC93475),
          gradientAlpha: 0,
          uiFontFamily: 'Press Start 2P',
          entryFontFamily: 'VT323',
          entryFontWeight: 400,
          borderRadius: 8,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF090B1A),
          textColor: const Color(0xFFFFF0C6),
          accentColor: const Color(0xFFFF4F9A),
          gradientAlpha: 0,
          uiFontFamily: 'Press Start 2P',
          entryFontFamily: 'VT323',
          entryFontWeight: 400,
          borderRadius: 8,
        ),
      ),
      LauncherDesign.toon.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFFFF0D8),
          textColor: const Color(0xFF2D3035),
          accentColor: const Color(0xFFD36B1E),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow Condensed',
          entryFontFamily: 'Barlow Condensed',
          entryFontWeight: 600,
          borderRadius: 8,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF292C30),
          textColor: const Color(0xFFFFF3D6),
          accentColor: const Color(0xFFFFB642),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow Condensed',
          entryFontFamily: 'Barlow Condensed',
          entryFontWeight: 600,
          borderRadius: 8,
        ),
      ),
      LauncherDesign.phosphor.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
            background: const Color(0xFFE8F0EB),
            textColor: const Color(0xFF1E3328),
            accentColor: const Color(0xFF168347),
            gradientAlpha: 0,
            uiFontFamily: 'Consolas',
            entryFontFamily: 'Consolas',
            entryFontWeight: 400,
            borderRadius: 0),
        darkTheme: defaultThemeColors(
            background: const Color(0xFF090F0E),
            textColor: const Color(0xFFDCE3DF),
            accentColor: const Color(0xFF58EF92),
            gradientAlpha: 0,
            uiFontFamily: 'Consolas',
            entryFontFamily: 'Consolas',
            entryFontWeight: 400,
            borderRadius: 0),
      ),
      LauncherDesign.strata.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
            background: const Color(0xFFEAF1F3),
            textColor: const Color(0xFF243640),
            accentColor: const Color(0xFF008B95),
            gradientAlpha: 0,
            uiFontFamily: 'Segoe UI',
            entryFontFamily: 'Segoe UI',
            entryFontWeight: 400,
            borderRadius: 12),
        darkTheme: defaultThemeColors(
            background: const Color(0xFF0C151A),
            textColor: const Color(0xFFEEF3F7),
            accentColor: const Color(0xFF20DFE3),
            gradientAlpha: 0,
            uiFontFamily: 'Segoe UI',
            entryFontFamily: 'Segoe UI',
            entryFontWeight: 400,
            borderRadius: 12),
      ),
      LauncherDesign.aurora.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
            background: const Color(0xFF031722),
            textColor: const Color(0xFFE4F5FF),
            accentColor: const Color(0xFF00E5F5),
            gradientAlpha: 0,
            uiFontFamily: 'Segoe UI',
            entryFontFamily: 'Segoe UI',
            entryFontWeight: 400,
            borderRadius: 18),
        darkTheme: defaultThemeColors(
            background: const Color(0xFF031722),
            textColor: const Color(0xFFE4F5FF),
            accentColor: const Color(0xFF00E5F5),
            gradientAlpha: 0,
            uiFontFamily: 'Segoe UI',
            entryFontFamily: 'Segoe UI',
            entryFontWeight: 400,
            borderRadius: 18),
      ),
      LauncherDesign.newCast.displayName: LauncherDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFF1C1C1E),
          textColor: const Color(0xFFF2F2F7),
          accentColor: const Color(0xFF0A84FF),
          gradientAlpha: 0,
          uiFontFamily: 'Segoe UI Variable Text',
          entryFontFamily: 'Segoe UI Variable Text',
          entryFontWeight: 600,
          borderRadius: 14,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF1C1C1E),
          textColor: const Color(0xFFF2F2F7),
          accentColor: const Color(0xFF0A84FF),
          gradientAlpha: 0,
          uiFontFamily: 'Segoe UI Variable Text',
          entryFontFamily: 'Segoe UI Variable Text',
          entryFontWeight: 600,
          borderRadius: 14,
        ),
      ),
    };
  }

  static Map<String, QMDesignThemeSet> createDefaultQuickMenuDesignThemes() {
    return <String, QMDesignThemeSet>{
      QuickMenuDesigns.crt.displayName: QMDesignThemeSet(
          lightTheme: defaultThemeColors(
              background: const Color(0xFFF8F4EC), // Warm white phosphor paper
              textColor: const Color(0xFF3A2B1F), // Dark brown terminal ink
              accentColor: const Color(0xFF9A4F14), // Readable amber-brown accent
              gradientAlpha: 0,
              uiFontFamily: 'Consolas',
              entryFontFamily: 'Consolas',
              entryFontWeight: 400,
              borderRadius: 18),
          darkTheme: defaultThemeColors(
              background: const Color(0xFF130F09),
              textColor: const Color(0xFFFFDDA0),
              accentColor: const Color(0xFFFFBE62),
              gradientAlpha: 0,
              uiFontFamily: 'Consolas',
              entryFontFamily: 'Consolas',
              entryFontWeight: 400,
              borderRadius: 18)),
      QuickMenuDesigns.retro.displayName: QMDesignThemeSet(
          lightTheme: defaultThemeColors(
              background: const Color(0xFFFFF5FA), // Pink-tinted arcade white
              textColor: const Color(0xFF2E2034), // Deep plum for pixel text
              accentColor: const Color(0xFFC21E68), // High-contrast arcade pink
              gradientAlpha: 0,
              uiFontFamily: 'Jura',
              entryFontFamily: 'Jura',
              entryFontWeight: 400,
              borderRadius: 8,
              baseFontSize: 11),
          darkTheme: defaultThemeColors(
              background: const Color(0xFF090B1A),
              textColor: const Color(0xFFFFF0C6),
              accentColor: const Color(0xFFFF4F9A),
              gradientAlpha: 0,
              uiFontFamily: 'Jura',
              entryFontFamily: 'Jura',
              entryFontWeight: 400,
              borderRadius: 8,
              baseFontSize: 11)),
      QuickMenuDesigns.superMario.displayName: QMDesignThemeSet(
          lightTheme: defaultThemeColors(
              background: const Color(0xFFF3F8FF), // Bright overworld sky
              textColor: const Color(0xFF17325B), // Deep blue game-menu ink
              accentColor: const Color(0xFFB05A00), // Darkened coin-gold accent
              gradientAlpha: 0,
              uiFontFamily: 'Jura',
              entryFontFamily: 'Jura',
              entryFontWeight: 400,
              borderRadius: 2),
          darkTheme: defaultThemeColors(
              background: const Color(0xFF15264A),
              textColor: const Color(0xFFFCF4DC),
              accentColor: const Color(0xFFF8C840),
              gradientAlpha: 0,
              uiFontFamily: 'Jura',
              entryFontFamily: 'Jura',
              entryFontWeight: 400,
              borderRadius: 2)),
      QuickMenuDesigns.modern.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffD5E0FB),
          textColor: const Color(0xff3A404A),
          accentColor: const Color(0xff446EE9),
          gradientAlpha: 200,
          uiFontFamily: 'Jura',
          entryFontFamily: 'Jura',
          borderRadius: 12,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF0A0A0A),
          textColor: const Color(0xFFFAF9F8),
          accentColor: const Color(0xFFA7CF3F),
          gradientAlpha: 20,
          uiFontFamily: 'Jura',
          entryFontFamily: 'Jura',
          borderRadius: 12,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.classic.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffECE2D7),
          textColor: const Color(0xff3D342B),
          accentColor: const Color(0xffB86F43),
          gradientAlpha: 150,
          uiFontFamily: 'Jura',
          entryFontFamily: 'Jura',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff171317),
          textColor: const Color(0xFFF5EFE7),
          accentColor: const Color(0xFFE4A768),
          gradientAlpha: 205,
          uiFontFamily: 'Jura',
          entryFontFamily: 'Jura',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.interface.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffEEF4F8),
          textColor: const Color(0xff223444),
          accentColor: const Color(0xff2D84B8),
          gradientAlpha: 220,
          uiFontFamily: 'Jura',
          uiFontWeight: 500,
          entryFontFamily: 'Jura',
          entryFontWeight: 700,
          borderRadius: 22,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff101923),
          textColor: const Color(0xFFEAF4FB),
          accentColor: const Color(0xFF68C9FF),
          gradientAlpha: 228,
          uiFontFamily: 'Jura',
          uiFontWeight: 500,
          entryFontFamily: 'Jura',
          entryFontWeight: 700,
          borderRadius: 22,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.matrix.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF2F2F2),
          textColor: const Color(0xff003B00),
          accentColor: const Color(0xff008F11),
          gradientAlpha: 0,
          uiFontFamily: 'Jura',
          uiFontWeight: 500,
          entryFontFamily: 'Jura',
          entryFontWeight: 700,
          borderRadius: 12,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff000000),
          textColor: const Color(0xff00FF41),
          accentColor: const Color(0xff008F11),
          gradientAlpha: 0,
          uiFontFamily: 'Jura',
          uiFontWeight: 500,
          entryFontFamily: 'Jura',
          entryFontWeight: 700,
          borderRadius: 12,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.serene.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF5F0EB),
          textColor: const Color(0xff2C2118),
          accentColor: const Color(0xffB07D4F),
          gradientAlpha: 180,
          uiFontFamily: 'Nunito',
          uiFontWeight: 400,
          entryFontFamily: 'Nunito',
          entryFontWeight: 600,
          borderRadius: 10,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff161618),
          textColor: const Color(0xffEDE8E3),
          accentColor: const Color(0xff445E91),
          gradientAlpha: 58,
          uiFontFamily: 'Nunito',
          uiFontWeight: 400,
          entryFontFamily: 'Nunito',
          entryFontWeight: 600,
          borderRadius: 10,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.aurora.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xff080706),
          textColor: const Color(0xff241B3A),
          accentColor: const Color(0xffC9D0D0),
          gradientAlpha: 0,
          uiFontFamily: 'Sora',
          uiFontWeight: 500,
          entryFontFamily: 'Sora',
          entryFontWeight: 600,
          borderRadius: 14,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff0B0B14),
          textColor: const Color(0xffEDEAFB),
          accentColor: const Color(0xff9B83FF),
          gradientAlpha: 78,
          uiFontFamily: 'Sora',
          uiFontWeight: 500,
          entryFontFamily: 'Sora',
          entryFontWeight: 600,
          borderRadius: 14,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.terminal.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFF1E1E1E),
          textColor: const Color(0xFFD4D4D4),
          accentColor: const Color(0xFF00C7FF),
          gradientAlpha: 0,
          uiFontFamily: 'JetBrains Mono',
          uiFontWeight: 500,
          entryFontFamily: 'JetBrains Mono',
          entryFontWeight: 600,
          borderRadius: 4,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF0C0C0C),
          textColor: const Color(0xFFCCCCCC),
          accentColor: const Color(0xFF39D353),
          gradientAlpha: 0,
          uiFontFamily: 'JetBrains Mono',
          uiFontWeight: 500,
          entryFontFamily: 'JetBrains Mono',
          entryFontWeight: 600,
          borderRadius: 4,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.terminal2.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFF1E1E1E),
          textColor: const Color(0xFFD4D4D4),
          accentColor: const Color(0xFF00C7FF),
          gradientAlpha: 0,
          uiFontFamily: 'JetBrains Mono',
          uiFontWeight: 500,
          entryFontFamily: 'JetBrains Mono',
          entryFontWeight: 600,
          borderRadius: 4,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF0C0C0C),
          textColor: const Color(0xFFCCCCCC),
          accentColor: const Color(0xFF39D353),
          gradientAlpha: 0,
          uiFontFamily: 'JetBrains Mono',
          uiFontWeight: 500,
          entryFontFamily: 'JetBrains Mono',
          entryFontWeight: 600,
          borderRadius: 4,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.tui.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF2F2F2),
          textColor: const Color(0xFF0C0C0C),
          accentColor: const Color(0xFF0037DA),
          gradientAlpha: 0,
          uiFontFamily: 'Consolas',
          entryFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontWeight: 400,
          borderRadius: 0,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF0C0C0C),
          textColor: const Color(0xFFCCCCCC),
          accentColor: const Color(0xFFCCCCCC),
          gradientAlpha: 0,
          uiFontFamily: 'Consolas',
          entryFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontWeight: 400,
          borderRadius: 0,
        ),
      ),
      QuickMenuDesigns.cassette.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffD9D2C3),
          textColor: const Color(0xff3B3428),
          accentColor: const Color(0xffC2551E),
          gradientAlpha: 110,
          uiFontFamily: 'Jura',
          uiFontWeight: 600,
          entryFontFamily: 'Jura',
          entryFontWeight: 700,
          borderRadius: 14,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff17130E),
          textColor: const Color(0xffEAD9B4),
          accentColor: const Color(0xffFFB000),
          gradientAlpha: 140,
          uiFontFamily: 'Jura',
          uiFontWeight: 600,
          entryFontFamily: 'Jura',
          entryFontWeight: 700,
          borderRadius: 14,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.fluent.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF3F3F3),
          textColor: const Color(0xff1B1B1B),
          accentColor: const Color(0xff005FB8),
          gradientAlpha: 60,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 600,
          borderRadius: 8,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff202020),
          textColor: const Color(0xffFFFFFF),
          accentColor: const Color(0xff60CDFF),
          gradientAlpha: 60,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 600,
          borderRadius: 8,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.gazette.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF6F1E5),
          textColor: const Color(0xff26211A),
          accentColor: const Color(0xffA3271E),
          gradientAlpha: 120,
          uiFontFamily: 'Georgia',
          uiFontWeight: 400,
          entryFontFamily: 'Georgia',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff1C1913),
          textColor: const Color(0xffE9E1CE),
          accentColor: const Color(0xffD8563F),
          gradientAlpha: 120,
          uiFontFamily: 'Georgia',
          uiFontWeight: 400,
          entryFontFamily: 'Georgia',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.player.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffC7CBD4),
          textColor: const Color(0xff23262C),
          accentColor: const Color(0xff2F6FD6),
          gradientAlpha: 120,
          uiFontFamily: 'Tahoma',
          uiFontWeight: 400,
          entryFontFamily: 'Tahoma',
          entryFontWeight: 700,
          borderRadius: 6,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff31353D),
          textColor: const Color(0xffD9DEE7),
          accentColor: const Color(0xff53C4EF),
          gradientAlpha: 140,
          uiFontFamily: 'Tahoma',
          uiFontWeight: 400,
          entryFontFamily: 'Tahoma',
          entryFontWeight: 700,
          borderRadius: 6,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.steam.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffDFE7EF),
          textColor: const Color(0xff1B2838),
          accentColor: const Color(0xff1A9FFF),
          gradientAlpha: 90,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 600,
          borderRadius: 4,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff1B2838),
          textColor: const Color(0xffC7D5E0),
          accentColor: const Color(0xff66C0F4),
          gradientAlpha: 90,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 600,
          borderRadius: 4,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.manifesto.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF2EEDB),
          textColor: const Color(0xff171713),
          accentColor: const Color(0xffE13A27),
          gradientAlpha: 0,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 500,
          entryFontFamily: 'Bahnschrift',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff171713),
          textColor: const Color(0xffF2EEDB),
          accentColor: const Color(0xffF0D83A),
          gradientAlpha: 0,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 500,
          entryFontFamily: 'Bahnschrift',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.vector.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffEEF3EE),
          textColor: const Color(0xff15211B),
          accentColor: const Color(0xff0C7A45),
          gradientAlpha: 55,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff0B100E),
          textColor: const Color(0xffCFE3D6),
          accentColor: const Color(0xff3CE68C),
          gradientAlpha: 70,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.ledger.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF3EDDC),
          textColor: const Color(0xff2B2419),
          accentColor: const Color(0xff8C2F1E),
          gradientAlpha: 45,
          uiFontFamily: 'Courier New',
          uiFontWeight: 400,
          entryFontFamily: 'Courier New',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff17130F),
          textColor: const Color(0xffE7DCC0),
          accentColor: const Color(0xffD9812E),
          gradientAlpha: 62,
          uiFontFamily: 'Courier New',
          uiFontWeight: 400,
          entryFontFamily: 'Courier New',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.console.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffDCDFE2),
          textColor: const Color(0xff23272B),
          accentColor: const Color(0xffD98A2B),
          gradientAlpha: 40,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 500,
          entryFontFamily: 'Bahnschrift',
          entryFontWeight: 700,
          borderRadius: 6,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff1B1D1F),
          textColor: const Color(0xffC9CDD1),
          accentColor: const Color(0xff36D6C4),
          gradientAlpha: 55,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 500,
          entryFontFamily: 'Bahnschrift',
          entryFontWeight: 700,
          borderRadius: 6,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.console2.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF3F3F3), // Win terminal "Campbell Light" paper
          textColor: const Color(0xff0C0C0C), // near-black console text
          accentColor: const Color(0xff0037DA), // classic cmd.exe blue
          gradientAlpha: 0, // flat — no glow/gradient
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff0C0C0C), // cmd.exe black
          textColor: const Color(0xffCCCCCC), // cmd.exe light gray
          accentColor: const Color(0xff16C60C), // cmd.exe bright green
          gradientAlpha: 0,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.foundry.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffE7E2D8),
          textColor: const Color(0xff2B2A26),
          accentColor: const Color(0xffA5472A),
          gradientAlpha: 48,
          uiFontFamily: 'Aldrich',
          uiFontWeight: 500,
          entryFontFamily: 'Aldrich',
          entryFontWeight: 700,
          borderRadius: 4,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff171816),
          textColor: const Color(0xffDDD9CF),
          accentColor: const Color(0xffD96D3B),
          gradientAlpha: 65,
          uiFontFamily: 'Aldrich',
          uiFontWeight: 500,
          entryFontFamily: 'Aldrich',
          entryFontWeight: 700,
          borderRadius: 4,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.anime.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffFFF3F8),
          textColor: const Color(0xff4A2E3B),
          accentColor: const Color(0xffFF6FA3),
          gradientAlpha: 90,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 600,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 700,
          borderRadius: 14,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff211622),
          textColor: const Color(0xffF7D9E6),
          accentColor: const Color(0xffFF8FC0),
          gradientAlpha: 110,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 600,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 700,
          borderRadius: 14,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.cyber.name: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF3E8FF), // Soft lavender blush
          textColor: const Color(0xff3B0764), // Deep violet
          accentColor: const Color(0xffD946EF), // Fuchsia neon
          gradientAlpha: 65,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 500,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 700,
          borderRadius: 2, // Sharp, mecha-style corners
          baseFontSize: 11,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff050217), // Near-black with blue tint
          textColor: const Color(0xffE2E8F0), // Slate-100
          accentColor: const Color(0xff22D3EE), // Cyan neon
          gradientAlpha: 90,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 500,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 700,
          borderRadius: 2,
          baseFontSize: 11,
        ),
      ),
      QuickMenuDesigns.tech.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF8FAFC), // Clean slate
          textColor: const Color(0xff1E293B), // Deep navy/slate
          accentColor: const Color(0xff2563EB), // Electric blue
          gradientAlpha: 50,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 600,
          borderRadius: 12, // Modern, soft rounded corners
          baseFontSize: 11,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff0B1120), // Deep space blue/black
          textColor: const Color(0xffE2E8F0), // Crisp off-white
          accentColor: const Color(0xff38BDF8), // Bright sky blue
          gradientAlpha: 70,
          uiFontFamily: 'Segoe UI',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI',
          entryFontWeight: 600,
          borderRadius: 12,
          baseFontSize: 11,
        ),
      ),
      QuickMenuDesigns.manga.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF7F3EA), // aged manga page
          textColor: const Color(0xff1B1B1B), // ink black
          accentColor: const Color(0xffD62839), // classic "impact" red
          gradientAlpha: 45,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 700,
          entryFontFamily: 'Bahnschrift',
          entryFontWeight: 800,
          borderRadius: 0,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff121212), // noir black page
          textColor: const Color(0xffECECEC), // paper white ink
          accentColor: const Color(0xffFF3B4E), // pop red glowing on black
          gradientAlpha: 85,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 700,
          entryFontFamily: 'Bahnschrift',
          entryFontWeight: 800,
          borderRadius: 0,
          baseFontSize: 10,
        ),
      ),
      // QuickMenuDesigns.impact.displayName: QMDesignThemeSet(
      //   lightTheme: _defaultThemeColors(
      //     background: const Color(0xffFFFCF6), // manga paper white
      //     textColor: const Color(0xff17171B), // ink black
      //     accentColor: const Color(0xffE8354C), // shonen red
      //     gradientAlpha: 60,
      //     uiFontFamily: 'Segoe UI',
      //     uiFontWeight: 600,
      //     entryFontFamily: 'Segoe UI',
      //     entryFontWeight: 800,
      //     borderRadius: 2,
      //     baseFontSize: 10,
      //   ),
      //   darkTheme: _defaultThemeColors(
      //     background: const Color(0xff0C0C11), // night-arc black
      //     textColor: const Color(0xffF3F3F6),
      //     accentColor: const Color(0xff35E6E0), // electric cyan
      //     gradientAlpha: 75,
      //     uiFontFamily: 'Segoe UI',
      //     uiFontWeight: 600,
      //     entryFontFamily: 'Segoe UI',
      //     entryFontWeight: 800,
      //     borderRadius: 2,
      //     baseFontSize: 10,
      //   ),
      // ),
      QuickMenuDesigns.outrun.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffF8F0FF), // Very light pastel lavender
          textColor: const Color(0xff1A0B2E), // Deep purple
          accentColor: const Color(0xffD300C5), // Hot magenta
          gradientAlpha: 60,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 2, // Sharp retro edges
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff0D0221), // Deep midnight purple
          textColor: const Color(0xffE0AAFF), // Soft neon lavender
          accentColor: const Color(0xff05D9E8), // Electric cyan
          gradientAlpha: 85,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 2,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.anime2.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffFFF5FA),
          textColor: const Color(0xff2D182E),
          accentColor: const Color(0xffE85D9A),
          gradientAlpha: 55,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 12,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff1A0F1E),
          textColor: const Color(0xffF8D4E8),
          accentColor: const Color(0xffFF7EB9),
          gradientAlpha: 70,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 12,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.outrun2.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xff2D1B4E), // Twilight purple
          textColor: const Color(0xff00F0FF), // Electric cyan
          accentColor: const Color(0xffFF00AA), // Hot magenta
          gradientAlpha: 55,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 2, // Sharp 80s CRT angles
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff0A0514), // Midnight void
          textColor: const Color(0xff00F0FF), // Electric cyan
          accentColor: const Color(0xffFF00AA), // Hot magenta
          gradientAlpha: 70,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 2,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.winamp.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xffD6D2CE), // Brushed aluminium
          textColor: const Color(0xff1A1A1A), // Dark pixel readout
          accentColor: const Color(0xff00C853), // LED green
          gradientAlpha: 55,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 1, // Sharp Winamp corners
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xff1E1E1E), // Charcoal chassis
          textColor: const Color(0xffC0C0C0), // Silver LCD text
          accentColor: const Color(0xff00FF41), // Bright LED green
          gradientAlpha: 70,
          uiFontFamily: 'Consolas',
          uiFontWeight: 400,
          entryFontFamily: 'Consolas',
          entryFontWeight: 700,
          borderRadius: 1,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.windowsXp.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFECE9D8),
          textColor: const Color(0xFF000000),
          accentColor: const Color(0xFF245EDC),
          gradientAlpha: 255,
          uiFontFamily: 'Tahoma',
          uiFontWeight: 400,
          entryFontFamily: 'Tahoma',
          entryFontWeight: 700,
          borderRadius: 7,
          baseFontSize: 10,
        ),
        // XP never shipped with a dark Luna shell. Keep the authentic palette
        // when the host application follows the system dark-mode setting.
        darkTheme: defaultThemeColors(
          background: const Color(0xFFECE9D8),
          textColor: const Color(0xFF000000),
          accentColor: const Color(0xFF245EDC),
          gradientAlpha: 255,
          uiFontFamily: 'Tahoma',
          uiFontWeight: 400,
          entryFontFamily: 'Tahoma',
          entryFontWeight: 700,
          borderRadius: 7,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.windows98.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFC0C0C0),
          textColor: const Color(0xFF000000),
          accentColor: const Color(0xFF000080),
          gradientAlpha: 0,
          uiFontFamily: 'MS Sans Serif',
          uiFontWeight: 400,
          entryFontFamily: 'MS Sans Serif',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFFC0C0C0),
          textColor: const Color(0xFF000000),
          accentColor: const Color(0xFF000080),
          gradientAlpha: 0,
          uiFontFamily: 'MS Sans Serif',
          uiFontWeight: 400,
          entryFontFamily: 'MS Sans Serif',
          entryFontWeight: 700,
          borderRadius: 0,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.notion.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF7F6F3),
          textColor: const Color(0xFF37352F),
          accentColor: const Color(0xFF2383E2),
          gradientAlpha: 0,
          uiFontFamily: 'Segoe UI Variable Text',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI Variable Text',
          entryFontWeight: 600,
          borderRadius: 8,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF191919),
          textColor: const Color(0xFFE6E6E6),
          accentColor: const Color(0xFF529CCA),
          gradientAlpha: 0,
          uiFontFamily: 'Segoe UI Variable Text',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI Variable Text',
          entryFontWeight: 600,
          borderRadius: 8,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.rundown.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFE9ECE4),
          textColor: const Color(0xFF20251F),
          accentColor: const Color(0xFF5C782E),
          gradientAlpha: 58,
          uiFontFamily: 'Barlow Semi Condensed',
          uiFontWeight: 500,
          entryFontFamily: 'Barlow Semi Condensed',
          entryFontWeight: 500,
          borderRadius: 5,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF171A17),
          textColor: const Color(0xFFDCE2D7),
          accentColor: const Color(0xFFA6C968),
          gradientAlpha: 72,
          uiFontFamily: 'Barlow Semi Condensed',
          uiFontWeight: 400,
          entryFontFamily: 'Barlow Semi Condensed',
          entryFontWeight: 500,
          borderRadius: 5,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.commandDeck.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFE8E9E2),
          textColor: const Color(0xFF171A17),
          accentColor: const Color(0xFF2F6B50),
          gradientAlpha: 28,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 500,
          entryFontFamily: 'Segoe UI Variable Text',
          entryFontWeight: 600,
          borderRadius: 4,
          baseFontSize: 10,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF151815),
          textColor: const Color(0xFFE4E8DE),
          accentColor: const Color(0xFFC3E56A),
          gradientAlpha: 36,
          uiFontFamily: 'Bahnschrift',
          uiFontWeight: 400,
          entryFontFamily: 'Segoe UI Variable Text',
          entryFontWeight: 600,
          borderRadius: 4,
          baseFontSize: 10,
        ),
      ),
      QuickMenuDesigns.switchboard.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFEFEAE2),
          textColor: const Color(0xFF332E29),
          accentColor: const Color(0xFFA64228),
          gradientAlpha: 0,
          uiFontFamily: 'Chivo',
          uiFontWeight: 400,
          entryFontFamily: 'Hanken Grotesk',
          entryFontWeight: 500,
          borderRadius: 12,
          baseFontSize: 11,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF242321),
          textColor: const Color(0xFFECE6DD),
          accentColor: const Color(0xFFE7AD78),
          gradientAlpha: 0,
          uiFontFamily: 'Chivo',
          uiFontWeight: 400,
          entryFontFamily: 'Hanken Grotesk',
          entryFontWeight: 500,
          borderRadius: 12,
          baseFontSize: 11,
        ),
      ),
      QuickMenuDesigns.orbit.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF0EDF3),
          textColor: const Color(0xFF332D3B),
          accentColor: const Color(0xFF74508D),
          gradientAlpha: 0,
          uiFontFamily: 'Gabarito',
          uiFontWeight: 400,
          entryFontFamily: 'Geologica',
          entryFontWeight: 400,
          borderRadius: 24,
          baseFontSize: 11,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF29252F),
          textColor: const Color(0xFFEAE3F0),
          accentColor: const Color(0xFFCAB0DE),
          gradientAlpha: 0,
          uiFontFamily: 'Gabarito',
          uiFontWeight: 400,
          entryFontFamily: 'Geologica',
          entryFontWeight: 400,
          borderRadius: 24,
          baseFontSize: 11,
        ),
      ),
      QuickMenuDesigns.ivoryGrove.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF0EADF),
          textColor: const Color(0xFF39362F),
          accentColor: const Color(0xFFAC8845),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 600,
          borderRadius: 20,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF292720),
          textColor: const Color(0xFFF0E9DC),
          accentColor: const Color(0xFFD0B477),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 600,
          borderRadius: 20,
        ),
      ),
      QuickMenuDesigns.ukiyoe.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF2E6CB),
          textColor: const Color(0xFF243C48),
          accentColor: const Color(0xFF244F6A),
          gradientAlpha: 0,
          uiFontFamily: 'Zen Kaku Gothic New',
          entryFontFamily: 'Zen Kaku Gothic New',
          entryFontWeight: 500,
          borderRadius: 6,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF1D2C35),
          textColor: const Color(0xFFE9DCC0),
          accentColor: const Color(0xFF8DAFBE),
          gradientAlpha: 0,
          uiFontFamily: 'Zen Kaku Gothic New',
          entryFontFamily: 'Zen Kaku Gothic New',
          entryFontWeight: 500,
          borderRadius: 6,
        ),
      ),
      QuickMenuDesigns.radiant.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFD5E0FB),
          textColor: const Color(0xFF3F4ED9),
          accentColor: const Color(0xFF168BFF),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 500,
          borderRadius: 22,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF03091F),
          textColor: const Color(0xFFDCE8FF),
          accentColor: const Color(0xFF168BFF),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 500,
          borderRadius: 22,
        ),
      ),
      QuickMenuDesigns.nouveau.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF5F1E8),
          textColor: const Color(0xFF30352B),
          accentColor: const Color(0xFF60684D),
          gradientAlpha: 0,
          uiFontFamily: 'Commissioner',
          entryFontFamily: 'Commissioner',
          entryFontWeight: 500,
          borderRadius: 18,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF23271F),
          textColor: const Color(0xFFF0EBDD),
          accentColor: const Color(0xFFB9C39B),
          gradientAlpha: 0,
          uiFontFamily: 'Commissioner',
          entryFontFamily: 'Commissioner',
          entryFontWeight: 500,
          borderRadius: 18,
        ),
      ),
      QuickMenuDesigns.satin.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFF0EFE9),
          textColor: const Color(0xFF303A36),
          accentColor: const Color(0xFF667C6E),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow',
          uiFontWeight: 500,
          entryFontFamily: 'Barlow',
          entryFontWeight: 500,
          borderRadius: 14,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF1C2320),
          textColor: const Color(0xFFE7EBE3),
          accentColor: const Color(0xFFA7BBA8),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow',
          uiFontWeight: 500,
          entryFontFamily: 'Barlow',
          entryFontWeight: 500,
          borderRadius: 14,
        ),
      ),
      QuickMenuDesigns.liquidMetal.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFE7EAED),
          textColor: const Color(0xFF2B3035),
          accentColor: const Color(0xFF626A73),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow',
          uiFontWeight: 500,
          entryFontFamily: 'Barlow',
          entryFontWeight: 500,
          borderRadius: 16,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF12151A),
          textColor: const Color(0xFFECEAE4),
          accentColor: const Color(0xFFCEC5AF),
          gradientAlpha: 0,
          uiFontFamily: 'Barlow',
          uiFontWeight: 500,
          entryFontFamily: 'Barlow',
          entryFontWeight: 500,
          borderRadius: 16,
        ),
      ),
      QuickMenuDesigns.opticalGlass.displayName: QMDesignThemeSet(
        lightTheme: defaultThemeColors(
          background: const Color(0xFFE5EAF2),
          textColor: const Color(0xFF202D45),
          accentColor: const Color(0xFF435B91),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 500,
          borderRadius: 24,
        ),
        darkTheme: defaultThemeColors(
          background: const Color(0xFF11151D),
          textColor: const Color(0xFFE6ECF7),
          accentColor: const Color(0xFF8AAEF5),
          gradientAlpha: 0,
          uiFontFamily: 'Mulish',
          entryFontFamily: 'Mulish',
          entryFontWeight: 500,
          borderRadius: 24,
        ),
      ),
    };
  }
}
