part of '../../launcher.dart';

mixin _LauncherThemeMixin on _LauncherStateMembersMixin {
  ThemeData _buildDesignTheme({
    required ThemeData baseTheme,
    required bool isDark,
    required Color accent,
  }) {
    final CapillaryTokens capillary = CapillaryTokens.resolve(isDark);
    return switch (_design) {
      LauncherDesign.thermal => _copyDesignTheme(baseTheme,
          brightness: ThermalTokens.isDark ? Brightness.dark : Brightness.light,
          surface: ThermalTokens.background,
          onSurface: ThermalTokens.foreground,
          primary: ThermalTokens.accent,
          highlightColor: ThermalTokens.rust,
          textTheme: GoogleFonts.hankenGroteskTextTheme(baseTheme.textTheme)),
      LauncherDesign.capillary => _copyDesignTheme(baseTheme,
          surface: capillary.background,
          onSurface: capillary.foreground,
          primary: capillary.accent,
          highlightColor: capillary.accent.withAlpha(30),
          textTheme: GoogleFonts.commissionerTextTheme(baseTheme.textTheme)),
      LauncherDesign.opticalGlass => _copyDesignTheme(baseTheme,
          brightness: OpticalGlassTokens.isDark ? Brightness.dark : Brightness.light,
          surface: OpticalGlassTokens.background,
          onSurface: OpticalGlassTokens.foreground,
          primary: OpticalGlassTokens.accent,
          highlightColor: OpticalGlassTokens.accent.withAlpha(30),
          textTheme: GoogleFonts.mulishTextTheme(baseTheme.textTheme)),
      LauncherDesign.liquidMetal => _copyDesignTheme(baseTheme,
          brightness: LiquidMetalTokens.isDark ? Brightness.dark : Brightness.light,
          surface: LiquidMetalTokens.background,
          onSurface: LiquidMetalTokens.foreground,
          primary: LiquidMetalTokens.accent,
          highlightColor: LiquidMetalTokens.accent.withAlpha(30),
          textTheme: GoogleFonts.barlowTextTheme(baseTheme.textTheme)),
      LauncherDesign.crt => _copyDesignTheme(baseTheme,
          brightness: CrtTokens.isDark ? Brightness.dark : Brightness.light,
          surface: CrtTokens.background,
          onSurface: CrtTokens.foreground,
          primary: CrtTokens.accent,
          highlightColor: CrtTokens.accent.withAlpha(30),
          textTheme: baseTheme.textTheme.apply(fontFamily: 'Consolas')),
      LauncherDesign.toon => _copyDesignTheme(
          baseTheme,
          brightness: ToonTokens.isDark ? Brightness.dark : Brightness.light,
          surface: ToonTokens.background,
          onSurface: ToonTokens.foreground,
          primary: ToonTokens.accent,
          highlightColor: ToonTokens.orange.withAlpha(42),
          textTheme: baseTheme.textTheme.apply(
            fontFamily: 'Barlow Condensed',
            fontFamilyFallback: const <String>['Segoe UI'],
          ),
        ),
      LauncherDesign.retro => _copyDesignTheme(
          baseTheme,
          brightness: RetroTokens.isDark ? Brightness.dark : Brightness.light,
          surface: RetroTokens.background,
          onSurface: RetroTokens.foreground,
          primary: RetroTokens.accent,
          highlightColor: RetroTokens.accent.withAlpha(30),
          textTheme: RetroTokens.resultTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.phosphor => _copyDesignTheme(baseTheme,
          brightness: PhosphorTokens.isDark ? Brightness.dark : Brightness.light,
          surface: PhosphorTokens.background,
          onSurface: PhosphorTokens.foreground,
          primary: PhosphorTokens.accent,
          highlightColor: PhosphorTokens.accent.withAlpha(30),
          textTheme: baseTheme.textTheme.apply(fontFamily: 'Consolas')),
      LauncherDesign.strata => _copyDesignTheme(baseTheme,
          brightness: StrataTokens.isDark ? Brightness.dark : Brightness.light,
          surface: StrataTokens.background,
          onSurface: StrataTokens.foreground,
          primary: StrataTokens.accent,
          highlightColor: StrataTokens.accent.withAlpha(30),
          textTheme: baseTheme.textTheme.apply(fontFamily: 'Segoe UI')),
      LauncherDesign.aurora => _copyDesignTheme(baseTheme,
          brightness: Brightness.dark,
          surface: AuroraTokens.background,
          onSurface: AuroraTokens.foreground,
          primary: AuroraTokens.accent,
          highlightColor: AuroraTokens.accent.withAlpha(30),
          textTheme: baseTheme.textTheme.apply(fontFamily: 'Segoe UI')),
      LauncherDesign.tui => _copyDesignTheme(
          baseTheme,
          surface: TuiTokens.background,
          onSurface: TuiTokens.foreground,
          primary: TuiTokens.accent,
          highlightColor: TuiTokens.foreground,
          textTheme: baseTheme.textTheme.apply(
            fontFamily: 'Consolas',
            fontFamilyFallback: const <String>['Lucida Console', 'monospace'],
          ),
        ),
      LauncherDesign.omarchy => _copyDesignTheme(
          baseTheme,
          surface: OmarchyTokens.bg,
          onSurface: OmarchyTokens.fg,
          primary: accent,
          highlightColor: OmarchyTokens.selected,
          textTheme: GoogleFonts.inconsolataTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.newCast => _copyDesignTheme(
          baseTheme,
          brightness: isDark ? Brightness.dark : Brightness.light,
          surface: RaycastTokens.surface(isDark),
          onSurface: RaycastTokens.primary(isDark),
          primary: RaycastTokens.primary(isDark),
          highlightColor: RaycastTokens.selected(isDark),
          textTheme: baseTheme.textTheme.apply(
            fontFamily: 'Segoe UI Variable Text',
            fontFamilyFallback: const <String>['Segoe UI', 'Arial'],
          ),
        ),
      LauncherDesign.windowsXp => _copyDesignTheme(
          baseTheme,
          surface: WindowsXpTokens.paper,
          onSurface: WindowsXpTokens.foreground,
          primary: WindowsXpTokens.selection,
          highlightColor: WindowsXpTokens.selection.withAlpha(34),
          textTheme: baseTheme.textTheme.apply(
            fontFamily: 'Tahoma',
            fontFamilyFallback: const <String>['Verdana', 'Segoe UI'],
          ),
        ),
      LauncherDesign.windows98 => _copyDesignTheme(
          baseTheme,
          surface: Windows98Tokens.face,
          onSurface: Windows98Tokens.foreground,
          primary: Windows98Tokens.selection,
          highlightColor: Windows98Tokens.selection.withAlpha(34),
          textTheme: baseTheme.textTheme.apply(
            fontFamily: 'MS Sans Serif',
            fontFamilyFallback: const <String>['Tahoma', 'Segoe UI'],
          ),
        ),
      LauncherDesign.notion => _copyDesignTheme(
          baseTheme,
          surface: NotionTokens.canvas(isDark),
          onSurface: NotionTokens.foreground(isDark),
          primary: NotionTokens.blue(isDark),
          highlightColor: NotionTokens.selection(isDark),
          textTheme: baseTheme.textTheme.apply(
            fontFamily: 'Segoe UI Variable Text',
            fontFamilyFallback: const <String>['Segoe UI'],
          ),
        ),
      LauncherDesign.terminal => _copyDesignTheme(
          baseTheme,
          surface: TerminalTokens.bg(isDark),
          onSurface: TerminalTokens.fg(isDark),
          highlightColor: accent.withAlpha(38),
          textTheme: GoogleFonts.jetBrainsMonoTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.terminal2 => _copyDesignTheme(
          baseTheme,
          surface: Terminal2Tokens.bg(isDark),
          onSurface: Terminal2Tokens.fg(isDark),
          highlightColor: accent.withAlpha(38),
          textTheme: GoogleFonts.fragmentMonoTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.zen => _copyDesignTheme(
          baseTheme,
          surface: ZenTokens.bg(isDark),
          onSurface: ZenTokens.fg(isDark),
          highlightColor: accent.withAlpha(isDark ? 42 : 30),
          textTheme: GoogleFonts.quicksandTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.blueprint => _copyDesignTheme(
          baseTheme,
          surface: BlueprintTokens.bg(isDark),
          onSurface: BlueprintTokens.fg(isDark),
          highlightColor: accent.withAlpha(34),
          textTheme: GoogleFonts.chakraPetchTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.transit => _copyDesignTheme(
          baseTheme,
          surface: TransitTokens.bg(isDark),
          onSurface: TransitTokens.fg(isDark),
          highlightColor: accent.withAlpha(30),
          textTheme: GoogleFonts.overpassTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.fluent => _copyDesignTheme(
          baseTheme,
          surface: FluentTokens.bg(isDark),
          onSurface: FluentTokens.fg(isDark),
          highlightColor: accent.withAlpha(28),
          textTheme: baseTheme.textTheme.apply(
            fontFamily: 'Segoe UI Variable Text',
            fontFamilyFallback: const <String>['Segoe UI'],
          ),
        ),
      LauncherDesign.manifesto => _copyDesignTheme(
          baseTheme,
          surface: ManifestoTokens.bg(isDark),
          onSurface: ManifestoTokens.fg(isDark),
          highlightColor: accent.withAlpha(32),
          textTheme: baseTheme.textTheme.apply(
            fontFamily: 'Segoe UI Variable Text',
            fontFamilyFallback: const <String>['Segoe UI'],
          ),
        ),
      LauncherDesign.orbit => _copyDesignTheme(
          baseTheme,
          surface: OrbitTokens.bg(isDark),
          onSurface: OrbitTokens.fg(isDark),
          highlightColor: accent.withAlpha(30),
          textTheme: GoogleFonts.spaceGroteskTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.relay => _copyDesignTheme(
          baseTheme,
          surface: RelayTokens.canvas(isDark, accent),
          onSurface: RelayTokens.foreground(isDark),
          highlightColor: accent.withAlpha(30),
          textTheme: GoogleFonts.encodeSansTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.switchboard => _copyDesignTheme(
          baseTheme,
          surface: SwitchboardTokens.canvas(isDark),
          onSurface: SwitchboardTokens.foreground(isDark),
          highlightColor: accent.withAlpha(28),
          textTheme: GoogleFonts.publicSansTextTheme(baseTheme.textTheme),
        ),
      LauncherDesign.glass => baseTheme.copyWith(
          textTheme: GoogleFonts.interTextTheme(baseTheme.textTheme),
        ),
      _ => baseTheme,
    };
  }

  ThemeData _copyDesignTheme(
    ThemeData baseTheme, {
    required Color surface,
    required Color onSurface,
    required Color highlightColor,
    required TextTheme textTheme,
    Color? primary,
    Brightness? brightness,
  }) {
    return baseTheme.copyWith(
      brightness: brightness,
      colorScheme: baseTheme.colorScheme.copyWith(
        brightness: brightness,
        surface: surface,
        onSurface: onSurface,
        primary: primary,
      ),
      highlightColor: highlightColor,
      textTheme: textTheme.apply(bodyColor: onSurface, displayColor: onSurface),
    );
  }
}
